In [110]:
import pandas as pd

In [111]:
df = pd.read_csv("../Data/Raw/global_retail_raw.csv")

In [112]:
df.head()

,Category,City,Country,Customer.ID,Customer.Name,Discount,Market,记录数,Order.Date,Order.ID,...,Sales,Segment,Ship.Date,Ship.Mode,Shipping.Cost,State,Sub.Category,Year,Market2,weeknum
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.0,US,1,2011-01-07 00:00:00.000,CA-2011-130813,...,19,Consumer,2011-01-09 00:00:00.000,Second Class,4.37,California,Paper,2011,North America,2
1,Office Supplies,Los Angeles,United States,MV-174854,Mark Van Huff,0.0,US,1,2011-01-21 00:00:00.000,CA-2011-148614,...,19,Consumer,2011-01-26 00:00:00.000,Standard Class,0.94,California,Paper,2011,North America,4
2,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05 00:00:00.000,CA-2011-118962,...,21,Consumer,2011-08-09 00:00:00.000,Standard Class,1.81,California,Paper,2011,North America,32
3,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05 00:00:00.000,CA-2011-118962,...,111,Consumer,2011-08-09 00:00:00.000,Standard Class,4.59,California,Paper,2011,North America,32
4,Office Supplies,Los Angeles,United States,AP-109154,Arthur Prichep,0.0,US,1,2011-09-29 00:00:00.000,CA-2011-146969,...,6,Consumer,2011-10-03 00:00:00.000,Standard Class,1.32,California,Paper,2011,North America,40

In [113]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 27 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Category        51290 non-null  object
 1   City            51290 non-null  object
 2   Country         51290 non-null  object
 3   Customer.ID     51290 non-null  object
 4   Customer.Name   51290 non-null  object
 5   Discount        51290 non-null  float64
 6   Market          51290 non-null  object
 7   记录数             51290 non-null  int64
 8   Order.Date      51290 non-null  object
 9   Order.ID        51290 non-null  object
 10  Order.Priority  51290 non-null  object
 11  Product.ID      51290 non-null  object
 12  Product.Name    51290 non-null  object
 13  Profit          51290 non-null  float64
 14  Quantity        51290 non-null  int64
 15  Region          51290 non-null  object
 16  Row.ID          51290 non-null  int64
 17  Sales           51290 non-null  int64
 18  Segment         51290 non-null  object
 19  Ship.Date       51290 non-null  object
 20  Ship.Mode       51290 non-null  object
 21  Shipping.Cost   51290 non-null  float64
 22  State           51290 non-null  object
 23  Sub.Category    51290 non-null  object
 24  Year            51290 non-null  int64
 25  Market2         51290 non-null  object
 26  weeknum         51290 non-null  int64
dtypes: float64(3), int64(6), object(18)
memory usage: 10.6+ MB

In [114]:
df.shape

(51290, 27)

In [115]:
df.columns = df.columns.str.strip()

df.columns = df.columns.str.lower()

df.columns = df.columns.str.replace(".", "_", regex=False)

In [116]:
df.columns

Index(['category', 'city', 'country', 'customer_id', 'customer_name',
       'discount', 'market', '记录数', 'order_date', 'order_id', 'order_priority',
       'product_id', 'product_name', 'profit', 'quantity', 'region', 'row_id',
       'sales', 'segment', 'ship_date', 'ship_mode', 'shipping_cost', 'state',
       'sub_category', 'year', 'market2', 'weeknum'],
      dtype='object')

In [151]:
df["记录数"].value_counts()

记录数
1    51290
Name: count, dtype: int64

In [152]:
df.drop(columns=["记录数"], inplace=True)

In [153]:
df["order_date"] = pd.to_datetime(df["order_date"])

In [154]:
df["order_date"].dtype

dtype('<M8[ns]')

In [155]:
df["ship_date"] = pd.to_datetime(df["ship_date"])

In [156]:
df["ship_date"].dtype

dtype('<M8[ns]')

In [157]:
df["delivery_days"] = (df["ship_date"] - df["order_date"]).dt.days

In [158]:
import numpy as np

df["profit_margin"] = np.where(
    df["sales"] == 0,
    0,
    (df["profit"] / df["sales"]) * 100
)

In [159]:
df["month"] = df["order_date"].dt.month_name()

In [160]:
df["month_no"] = df["order_date"].dt.month

In [161]:
df["quarter"] = df["order_date"].dt.quarter

In [162]:
df["day"] = df["order_date"].dt.day

In [163]:
df["year"] = df["order_date"].dt.year

In [164]:
df["year"] = df["order_date"].dt.year

In [165]:
df["week"] = df["order_date"].dt.isocalendar().week

In [166]:
df["is_weekend"] = df["order_date"].dt.dayofweek >= 5

In [167]:
df["discount_band"] = pd.cut(
    df["discount"],
    bins=[-0.01, 0, 0.1, 0.2, 0.3, 0.5, 1],
    labels=[
        "No Discount",
        "0-10%",
        "10-20%",
        "20-30%",
        "30-50%",
        "Above 50%"
    ]
)

In [168]:
df["loss_order"] = (df["profit"] < 0).astype(int)

In [169]:
df["high_discount"] = (df["discount"] >= 0.20).astype(int)

In [170]:
df["sales_bucket"] = pd.qcut(
    df["sales"],
    q=4,
    labels=["Low", "Medium", "High", "Very High"]
)

In [171]:
df["profit_bucket"] = pd.qcut(
    df["profit"],
    q=4,
    labels=["Low", "Medium", "High", "Very High"]
)

In [172]:
df["shipping_cost_bucket"] = pd.qcut(
    df["shipping_cost"],
    q=4,
    labels=["Low", "Medium", "High", "Very High"]
)

In [173]:
df["average_order_value"] = df["sales"] / df["quantity"]

In [174]:
df["shipping_cost_pct"] = np.where(
    df["sales"] == 0,
    0,
    (df["shipping_cost"] / df["sales"]) * 100
)

In [175]:
df["discount_amount"] = df["sales"] * df["discount"]

In [176]:
df["net_sales"] = df["sales"] - df["discount_amount"]

In [177]:
import numpy as np

In [178]:
df["profit_status"] = np.where(
    df["profit"] > 0,
    "Profit",
    np.where(df["profit"] == 0, "Break Even", "Loss")
)

In [179]:
df["delivery_status"] = np.where(
    df["delivery_days"] <= 3,
    "Fast",
    np.where(
        df["delivery_days"] <= 7,
        "Normal",
        "Delayed"
    )
)

In [180]:
df["profit_per_unit"] = df["profit"] / df["quantity"]

In [181]:
df[["product_name", "profit", "quantity", "profit_per_unit"]].head()

,product_name,profit,quantity,profit_per_unit
0,Xerox 225,9.3312,3,3.1104
1,"Wirebound Service Call Books, 5 1/2"" x 4""",9.2928,2,4.6464
2,"Adams Phone Message Book, Professional, 400 Me...",9.8418,3,3.2806
3,Xerox 1913,53.2608,2,26.6304
4,Xerox 223,3.1104,1,3.1104

In [182]:
df[[
    "delivery_days",
    "profit_margin",
    "month",
    "month_no",
    "quarter",
    "day",
    "year",
    "week",
    "is_weekend",
    "discount_band",
    "loss_order",
    "high_discount",
    "sales_bucket",
    "profit_bucket",
    "shipping_cost_bucket",
    "average_order_value",
    "shipping_cost_pct",
    "discount_amount",
    "net_sales",
    "profit_status",
    "delivery_status",
    "profit_per_unit"
]].head()

,delivery_days,profit_margin,month,month_no,quarter,day,year,week,is_weekend,discount_band,...,sales_bucket,profit_bucket,shipping_cost_bucket,average_order_value,shipping_cost_pct,discount_amount,net_sales,profit_status,delivery_status,profit_per_unit
0,2,49.111579,January,1,1,7,2011,1,False,No Discount,...,Low,High,Medium,6.333333,23.000000,0.0,19.0,Profit,Fast,3.1104
1,5,48.909474,January,1,1,21,2011,3,False,No Discount,...,Low,High,Low,9.500000,4.947368,0.0,19.0,Profit,Normal,4.6464
2,4,46.865714,August,8,3,5,2011,31,False,No Discount,...,Low,High,Low,7.000000,8.619048,0.0,21.0,Profit,Normal,3.2806
3,4,47.982703,August,8,3,5,2011,31,False,No Discount,...,High,Very High,Medium,55.500000,4.135135,0.0,111.0,Profit,Normal,26.6304
4,4,51.840000,September,9,3,29,2011,39,False,No Discount,...,Low,Medium,Low,6.000000,22.000000,0.0,6.0,Profit,Normal,3.1104

In [183]:
df.isnull().sum()

category                0
city                    0
country                 0
customer_id             0
customer_name           0
discount                0
market                  0
order_date              0
order_id                0
order_priority          0
product_id              0
product_name            0
profit                  0
quantity                0
region                  0
row_id                  0
sales                   0
segment                 0
ship_date               0
ship_mode               0
shipping_cost           0
state                   0
sub_category            0
year                    0
market2                 0
weeknum                 0
delivery_days           0
profit_margin           0
month                   0
month_no                0
quarter                 0
day                     0
week                    0
is_weekend              0
discount_band           0
loss_order              0
high_discount           0
sales_bucket            0
profit_bucket           0
shipping_cost_bucket    0
average_order_value     0
shipping_cost_pct       0
discount_amount         0
net_sales               0
profit_status           0
delivery_status         0
profit_per_unit         0
dtype: int64

In [184]:
df.duplicated().sum()

np.int64(0)

In [185]:
df.dtypes

category                        object
city                            object
country                         object
customer_id                     object
customer_name                   object
discount                       float64
market                          object
order_date              datetime64[ns]
order_id                        object
order_priority                  object
product_id                      object
product_name                    object
profit                         float64
quantity                         int64
region                          object
row_id                           int64
sales                            int64
segment                         object
ship_date               datetime64[ns]
ship_mode                       object
shipping_cost                  float64
state                           object
sub_category                    object
year                             int32
market2                         object
weeknum                          int64
delivery_days                    int64
profit_margin                  float64
month                           object
month_no                         int32
quarter                          int32
day                              int32
week                            UInt32
is_weekend                        bool
discount_band                 category
loss_order                       int64
high_discount                    int64
sales_bucket                  category
profit_bucket                 category
shipping_cost_bucket          category
average_order_value            float64
shipping_cost_pct              float64
discount_amount                float64
net_sales                      float64
profit_status                   object
delivery_status                 object
profit_per_unit                float64
dtype: object

In [186]:
df.describe().T

,count,mean,min,25%,50%,75%,max,std
discount,51290.0,0.142908,0.0,0.0,0.0,0.2,0.85,0.21228
order_date,51290,2013-05-11 21:26:49.155780864,2011-01-01 00:00:00,2012-06-19 00:00:00,2013-07-08 00:00:00,2014-05-22 00:00:00,2014-12-31 00:00:00,NaN
profit,51290.0,28.610982,-6599.978,0.0,9.24,36.81,8399.976,174.340972
quantity,51290.0,3.476545,1.0,2.0,3.0,5.0,14.0,2.278766
row_id,51290.0,25645.5,1.0,12823.25,25645.5,38467.75,51290.0,14806.29199
sales,51290.0,246.49844,0.0,31.0,85.0,251.0,22638.0,487.567175
ship_date,51290,2013-05-15 20:42:42.745174784,2011-01-03 00:00:00,2012-06-23 00:00:00,2013-07-12 00:00:00,2014-05-26 00:00:00,2015-01-07 00:00:00,NaN
shipping_cost,51290.0,26.375818,0.002,2.61,7.79,24.45,933.57,57.29681
year,51290.0,2012.777208,2011.0,2012.0,2013.0,2014.0,2014.0,1.098931
weeknum,51290.0,31.287112,1.0,20.0,33.0,44.0,53.0,14.429795
delivery_days,51290.0,3.96937,0.0,3.0,4.0,5.0,7.0,1.729437
profit_margin,51290.0,4.719877,-472.775207,0.0,16.924859,33.311107,58.28,46.684489
month_no,51290.0,7.522636,1.0,5.0,8.0,10.0,12.0,3.300056
quarter,51290.0,2.793235,1.0,2.0,3.0,4.0,4.0,1.066015
day,51290.0,15.78296,1.0,8.0,16.0,23.0,31.0,8.742164
week,51290.0,30.675687,1.0,20.0,33.0,44.0,52.0,14.535168
loss_order,51290.0,0.24457,0.0,0.0,0.0,0.0,1.0,0.429836
high_discount,51290.0,0.318308,0.0,0.0,0.0,1.0,1.0,0.465824
average_order_value,51290.0,71.659964,0.0,12.0,29.5,82.0,3773.0,113.581076
shipping_cost_pct,51290.0,10.924737,0.0,6.307297,9.022727,13.643015,59.005917,7.002215
discount_amount,51290.0,26.250249,0.0,0.0,0.0,15.5,11319.0,99.146484
net_sales,51290.0,220.248191,0.0,25.0,72.0,220.5,17500.0,447.021291
profit_per_unit,51290.0,8.122688,-1319.9956,0.0,3.39,12.24,1679.9952,43.338665

In [187]:
df["order_date"] = df["order_date"].dt.strftime("%Y-%m-%d")
df["ship_date"] = df["ship_date"].dt.strftime("%Y-%m-%d")

In [188]:
df.to_csv("../Data/Processed/cleaned_superstore.csv", index=False)