In [1]:
import pandas as pd
import numpy as np

In [2]:
retail = pd.read_csv("../Data/Processed/cleaned_superstore.csv")

In [3]:
retail.head()

,category,city,country,customer_id,customer_name,discount,market,order_date,order_id,order_priority,...,sales_bucket,profit_bucket,shipping_cost_bucket,average_order_value,shipping_cost_pct,discount_amount,net_sales,profit_status,delivery_status,profit_per_unit
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.0,US,07-01-2011,CA-2011-130813,High,...,Low,High,Medium,6.333333,23.000000,0.0,19.0,Profit,Fast,3.1104
1,Office Supplies,Los Angeles,United States,MV-174854,Mark Van Huff,0.0,US,21-01-2011,CA-2011-148614,Medium,...,Low,High,Low,9.500000,4.947368,0.0,19.0,Profit,Normal,4.6464
2,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,05-08-2011,CA-2011-118962,Medium,...,Low,High,Low,7.000000,8.619048,0.0,21.0,Profit,Normal,3.2806
3,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,05-08-2011,CA-2011-118962,Medium,...,High,Very High,Medium,55.500000,4.135135,0.0,111.0,Profit,Normal,26.6304
4,Office Supplies,Los Angeles,United States,AP-109154,Arthur Prichep,0.0,US,29-09-2011,CA-2011-146969,High,...,Low,Medium,Low,6.000000,22.000000,0.0,6.0,Profit,Normal,3.1104

In [4]:
retail.columns.tolist()

['category',
 'city',
 'country',
 'customer_id',
 'customer_name',
 'discount',
 'market',
 'order_date',
 'order_id',
 'order_priority',
 'product_id',
 'product_name',
 'profit',
 'quantity',
 'region',
 'row_id',
 'sales',
 'segment',
 'ship_date',
 'ship_mode',
 'shipping_cost',
 'state',
 'sub_category',
 'year',
 'market2',
 'weeknum',
 'delivery_days',
 'profit_margin',
 'month',
 'month_no',
 'quarter',
 'day',
 'week',
 'is_weekend',
 'discount_band',
 'loss_order',
 'high_discount',
 'sales_bucket',
 'profit_bucket',
 'shipping_cost_bucket',
 'average_order_value',
 'shipping_cost_pct',
 'discount_amount',
 'net_sales',
 'profit_status',
 'delivery_status',
 'profit_per_unit']

In [7]:
import os

os.getcwd()

'C:\\Users\\SHARVARI\\Downloads\\Retail_Profit_Leakage_Project\\Notebooks'

In [8]:
inflation = pd.read_csv(
    "../Data/External/World Bank Inflation/API_FP.CPI.TOTL.ZG_DS2_en_csv_v2_446435.csv",
    skiprows=4
)

In [9]:
inflation.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,-1.028282,3.626041,4.257462,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,6.221375,4.689806,4.102851,5.191629,6.824727,10.883478,7.399186,4.770857,NaN,NaN
2,Afghanistan,AFG,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,4.975952,0.626149,2.302373,5.601888,5.133203,13.712102,-4.644709,-6.601186,NaN,NaN
3,Africa Western and Central,AFW,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,1.725486,1.784050,1.983092,2.490378,3.745568,7.949251,5.221168,3.608044,NaN,NaN
4,Angola,AGO,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,29.844480,19.628938,17.080954,22.271539,25.754295,21.355290,13.644102,28.240495,NaN,NaN

In [10]:
inflation.columns.tolist()

['Country Name',
 'Country Code',
 'Indicator Name',
 'Indicator Code',
 '1960',
 '1961',
 '1962',
 '1963',
 '1964',
 '1965',
 '1966',
 '1967',
 '1968',
 '1969',
 '1970',
 '1971',
 '1972',
 '1973',
 '1974',
 '1975',
 '1976',
 '1977',
 '1978',
 '1979',
 '1980',
 '1981',
 '1982',
 '1983',
 '1984',
 '1985',
 '1986',
 '1987',
 '1988',
 '1989',
 '1990',
 '1991',
 '1992',
 '1993',
 '1994',
 '1995',
 '1996',
 '1997',
 '1998',
 '1999',
 '2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '2018',
 '2019',
 '2020',
 '2021',
 '2022',
 '2023',
 '2024',
 '2025',
 'Unnamed: 70']

In [11]:
inflation.shape

(266, 71)

In [12]:
inflation = inflation.drop(
    columns=[
        "Country Code",
        "Indicator Name",
        "Indicator Code",
        "Unnamed: 70"
    ]
)

In [13]:
inflation.head()

,Country Name,1960,1961,1962,1963,1964,1965,1966,1967,1968,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Aruba,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.931196,-1.028282,3.626041,4.257462,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.446877,6.221375,4.689806,4.102851,5.191629,6.824727,10.883478,7.399186,4.770857,NaN
2,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.383892,4.975952,0.626149,2.302373,5.601888,5.133203,13.712102,-4.644709,-6.601186,NaN
3,Africa Western and Central,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.487416,1.725486,1.784050,1.983092,2.490378,3.745568,7.949251,5.221168,3.608044,NaN
4,Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30.694415,29.844480,19.628938,17.080954,22.271539,25.754295,21.355290,13.644102,28.240495,NaN

In [14]:
inflation = inflation.melt(
    id_vars="Country Name",
    var_name="year",
    value_name="inflation_rate"
)

In [15]:
inflation.head()

                  Country Name  year  inflation_rate
0                        Aruba  1960             NaN
1  Africa Eastern and Southern  1960             NaN
2                  Afghanistan  1960             NaN
3   Africa Western and Central  1960             NaN
4                       Angola  1960             NaN

In [16]:
inflation["year"] = inflation["year"].astype(int)

In [20]:
min_year = retail["year"].min()
max_year = retail["year"].max()

inflation = inflation[
    inflation["year"].between(min_year, max_year)
]

In [21]:
inflation.head()

                      Country Name  year  inflation_rate
13566                        Aruba  2011        4.316297
13567  Africa Eastern and Southern  2011        8.971206
13568                  Afghanistan  2011       11.804186
13569   Africa Western and Central  2011        4.018699
13570                       Angola  2011       13.482468

In [22]:
inflation.shape

(1064, 3)

In [23]:
inflation = inflation.rename(
    columns={
        "Country Name": "country"
    }
)

In [24]:
inflation.columns

Index(['country', 'year', 'inflation_rate'], dtype='object')

In [25]:
pd.merge(retail, inflation, on=["country", "year"])

,category,city,country,customer_id,customer_name,discount,market,order_date,order_id,order_priority,...,profit_bucket,shipping_cost_bucket,average_order_value,shipping_cost_pct,discount_amount,net_sales,profit_status,delivery_status,profit_per_unit,inflation_rate
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.0,US,07-01-2011,CA-2011-130813,High,...,High,Medium,6.333333,23.000000,0.0,19.0,Profit,Fast,3.1104,3.156842
1,Office Supplies,Los Angeles,United States,MV-174854,Mark Van Huff,0.0,US,21-01-2011,CA-2011-148614,Medium,...,High,Low,9.500000,4.947368,0.0,19.0,Profit,Normal,4.6464,3.156842
2,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,05-08-2011,CA-2011-118962,Medium,...,High,Low,7.000000,8.619048,0.0,21.0,Profit,Normal,3.2806,3.156842
3,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,05-08-2011,CA-2011-118962,Medium,...,Very High,Medium,55.500000,4.135135,0.0,111.0,Profit,Normal,26.6304,3.156842
4,Office Supplies,Los Angeles,United States,AP-109154,Arthur Prichep,0.0,US,29-09-2011,CA-2011-146969,High,...,Medium,Low,6.000000,22.000000,0.0,6.0,Profit,Normal,3.1104,3.156842
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46973,Office Supplies,Los Angeles,United States,AM-103604,Alice McCarthy,0.2,US,03-12-2014,CA-2014-109701,High,...,High,Medium,34.500000,7.463768,13.8,55.2,Profit,Fast,11.2866,1.622223
46974,Office Supplies,Los Angeles,United States,AM-103604,Alice McCarthy,0.2,US,03-12-2014,CA-2014-109701,High,...,Medium,Low,1.500000,4.888889,1.8,7.2,Profit,Fast,0.5264,1.622223
46975,Office Supplies,Los Angeles,United States,HR-147704,Hallie Redmond,0.2,US,18-12-2014,CA-2014-106964,Medium,...,Medium,Low,6.000000,2.583333,2.4,9.6,Profit,Fast,2.1402,1.622223
46976,Office Supplies,Los Angeles,United States,RM-196754,Robert Marley,0.2,US,25-12-2014,CA-2014-145219,Critical,...,High,High,30.000000,17.722222,18.0,72.0,Profit,Fast,11.3100,1.622223
46977,Office Supplies,Los Angeles,United States,FH-143654,Fred Hopkins,0.2,US,26-12-2014,CA-2014-121398,Medium,...,Very High,High,51.333333,6.227273,30.8,123.2,Profit,Normal,17.2746,1.622223

In [26]:
retail_inflation = pd.merge(
    retail,
    inflation,
    on=["country", "year"],
    how="left"
)

retail_inflation["inflation_rate"].isnull().sum()

np.int64(5453)

In [27]:
retail_inflation[
    retail_inflation["inflation_rate"].isnull()
]["country"].unique()

array(['Hong Kong', 'Democratic Republic of the Congo', 'Cuba', 'Russia',
       'Egypt', 'Iran', 'Czech Republic', 'Kyrgyzstan', 'Syria',
       'Somalia', 'Guadeloupe', 'Taiwan', 'Martinique', 'Slovakia',
       'Republic of the Congo', 'Eritrea', 'Swaziland', 'Macedonia',
       'Turkey', 'Turkmenistan', 'Yemen', 'South Korea',
       'Myanmar (Burma)', 'Vietnam', 'Argentina', 'Venezuela'],
      dtype=object)

In [28]:
inflation[
    inflation["country"].str.contains("Hong|Russia|Egypt|Iran|Korea|Viet|Vene|Congo|Czech|Slovak|Maced|Burma|Swaz|Taiwan", case=False, na=False)
]["country"].unique()

array(['Congo, Dem. Rep.', 'Congo, Rep.', 'Czechia', 'Egypt, Arab Rep.',
       'Hong Kong SAR, China', 'Iran, Islamic Rep.', 'Korea, Rep.',
       'North Macedonia', "Korea, Dem. People's Rep.",
       'Russian Federation', 'Slovak Republic', 'Venezuela, RB',
       'Viet Nam'], dtype=object)

In [29]:
country_mapping = {
    "Hong Kong": "Hong Kong SAR, China",
    "Democratic Republic of the Congo": "Congo, Dem. Rep.",
    "Republic of the Congo": "Congo, Rep.",
    "Egypt": "Egypt, Arab Rep.",
    "Iran": "Iran, Islamic Rep.",
    "South Korea": "Korea, Rep.",
    "North Korea": "Korea, Dem. People's Rep.",
    "Russia": "Russian Federation",
    "Vietnam": "Viet Nam",
    "Venezuela": "Venezuela, RB",
    "Macedonia": "North Macedonia",
    "Czech Republic": "Czechia"
}

retail["country"] = retail["country"].replace(country_mapping)

In [30]:
retail_inflation = pd.merge(
    retail,
    inflation,
    on=["country", "year"],
    how="left"
)

In [31]:
retail_inflation["inflation_rate"].isnull().sum()

np.int64(2863)

In [32]:
retail_inflation[
    retail_inflation["inflation_rate"].isnull()
]["country"].value_counts()

country
Turkey             1378
Cuba                724
Argentina           390
Myanmar (Burma)     136
Somalia              52
Kyrgyzstan           40
Yemen                30
Syria                29
Martinique           25
Turkmenistan         25
Taiwan               14
Guadeloupe            8
Slovakia              8
Eritrea               2
Swaziland             2
Name: count, dtype: int64

In [33]:
country_mapping.update({
    "Turkey": "Türkiye",
    "Argentina": "Argentine Republic",
    "Myanmar (Burma)": "Myanmar",
    "Kyrgyzstan": "Kyrgyz Republic",
    "Slovakia": "Slovak Republic",
    "Swaziland": "Eswatini"
})

retail["country"] = retail["country"].replace(country_mapping)

In [34]:
retail_inflation = pd.merge(
    retail,
    inflation,
    on=["country", "year"],
    how="left"
)

In [35]:
retail_inflation["inflation_rate"].isnull().sum()

np.int64(2677)

In [36]:
inflation.to_csv(
    "../Data/Processed/inflation_cleaned.csv",
    index=False
)