In [1]:
import pandas as pd
import numpy as np

In [2]:
retail = pd.read_csv("../Data/Processed/cleaned_superstore.csv")

inflation = pd.read_csv("../Data/Processed/inflation_cleaned.csv")

gdp = pd.read_csv("../Data/Processed/gdp_growth_cleaned.csv")

In [3]:
print("Retail:", retail.shape)
print("Inflation:", inflation.shape)
print("GDP:", gdp.shape)

Retail: (51290, 47)
Inflation: (1064, 3)
GDP: (1064, 3)

In [4]:
print(retail.columns.tolist())
print(inflation.columns.tolist())
print(gdp.columns.tolist())

['category', 'city', 'country', 'customer_id', 'customer_name', 'discount', 'market', 'order_date', 'order_id', 'order_priority', 'product_id', 'product_name', 'profit', 'quantity', 'region', 'row_id', 'sales', 'segment', 'ship_date', 'ship_mode', 'shipping_cost', 'state', 'sub_category', 'year', 'market2', 'weeknum', 'delivery_days', 'profit_margin', 'month', 'month_no', 'quarter', 'day', 'week', 'is_weekend', 'discount_band', 'loss_order', 'high_discount', 'sales_bucket', 'profit_bucket', 'shipping_cost_bucket', 'average_order_value', 'shipping_cost_pct', 'discount_amount', 'net_sales', 'profit_status', 'delivery_status', 'profit_per_unit']
['country', 'year', 'inflation_rate']
['country', 'year', 'gdp_growth']

In [5]:
country_mapping = {
    "Hong Kong": "Hong Kong SAR, China",
    "Democratic Republic of the Congo": "Congo, Dem. Rep.",
    "Republic of the Congo": "Congo, Rep.",
    "Egypt": "Egypt, Arab Rep.",
    "Iran": "Iran, Islamic Rep.",
    "South Korea": "Korea, Rep.",
    "North Korea": "Korea, Dem. People's Rep.",
    "Russia": "Russian Federation",
    "Vietnam": "Viet Nam",
    "Venezuela": "Venezuela, RB",
    "Macedonia": "North Macedonia",
    "Czech Republic": "Czechia",
    "Turkey": "Turkiye",
    "Myanmar (Burma)": "Myanmar",
    "Kyrgyzstan": "Kyrgyz Republic",
    "Slovakia": "Slovak Republic",
    "Swaziland": "Eswatini"
}

retail["country"] = retail["country"].replace(country_mapping)

retail["country"] = retail["country"].replace({
    "Türkiye": "Turkiye"
})

In [6]:
final_df = pd.merge(
    retail,
    inflation,
    on=["country", "year"],
    how="left"
)

In [7]:
final_df = pd.merge(
    final_df,
    gdp,
    on=["country", "year"],
    how="left"
)

In [8]:
final_df.shape

(51290, 49)

In [9]:
final_df.head()

,category,city,country,customer_id,customer_name,discount,market,order_date,order_id,order_priority,...,shipping_cost_bucket,average_order_value,shipping_cost_pct,discount_amount,net_sales,profit_status,delivery_status,profit_per_unit,inflation_rate,gdp_growth
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.0,US,07-01-2011,CA-2011-130813,High,...,Medium,6.333333,23.000000,0.0,19.0,Profit,Fast,3.1104,3.156842,1.564407
1,Office Supplies,Los Angeles,United States,MV-174854,Mark Van Huff,0.0,US,21-01-2011,CA-2011-148614,Medium,...,Low,9.500000,4.947368,0.0,19.0,Profit,Normal,4.6464,3.156842,1.564407
2,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,05-08-2011,CA-2011-118962,Medium,...,Low,7.000000,8.619048,0.0,21.0,Profit,Normal,3.2806,3.156842,1.564407
3,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,05-08-2011,CA-2011-118962,Medium,...,Medium,55.500000,4.135135,0.0,111.0,Profit,Normal,26.6304,3.156842,1.564407
4,Office Supplies,Los Angeles,United States,AP-109154,Arthur Prichep,0.0,US,29-09-2011,CA-2011-146969,High,...,Low,6.000000,22.000000,0.0,6.0,Profit,Normal,3.1104,3.156842,1.564407

In [10]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 49 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   category              51290 non-null  object
 1   city                  51290 non-null  object
 2   country               51290 non-null  object
 3   customer_id           51290 non-null  object
 4   customer_name         51290 non-null  object
 5   discount              51290 non-null  float64
 6   market                51290 non-null  object
 7   order_date            51290 non-null  object
 8   order_id              51290 non-null  object
 9   order_priority        51290 non-null  object
 10  product_id            51290 non-null  object
 11  product_name          51290 non-null  object
 12  profit                51290 non-null  float64
 13  quantity              51290 non-null  int64
 14  region                51290 non-null  object
 15  row_id                51290 non-null  int64
 16  sales                 51290 non-null  int64
 17  segment               51290 non-null  object
 18  ship_date             51290 non-null  object
 19  ship_mode             51290 non-null  object
 20  shipping_cost         51290 non-null  float64
 21  state                 51290 non-null  object
 22  sub_category          51290 non-null  object
 23  year                  51290 non-null  int64
 24  market2               51290 non-null  object
 25  weeknum               51290 non-null  int64
 26  delivery_days         51290 non-null  int64
 27  profit_margin         51290 non-null  float64
 28  month                 51290 non-null  object
 29  month_no              51290 non-null  int64
 30  quarter               51290 non-null  int64
 31  day                   51290 non-null  int64
 32  week                  51290 non-null  int64
 33  is_weekend            51290 non-null  bool
 34  discount_band         51290 non-null  object
 35  loss_order            51290 non-null  int64
 36  high_discount         51290 non-null  int64
 37  sales_bucket          51290 non-null  object
 38  profit_bucket         51290 non-null  object
 39  shipping_cost_bucket  51290 non-null  object
 40  average_order_value   51290 non-null  float64
 41  shipping_cost_pct     51290 non-null  float64
 42  discount_amount       51290 non-null  float64
 43  net_sales             51290 non-null  float64
 44  profit_status         51290 non-null  object
 45  delivery_status       51290 non-null  object
 46  profit_per_unit       51290 non-null  float64
 47  inflation_rate        49991 non-null  float64
 48  gdp_growth            51118 non-null  float64
dtypes: bool(1), float64(11), int64(12), object(25)
memory usage: 18.8+ MB

In [11]:
final_df.isnull().sum()

category                   0
city                       0
country                    0
customer_id                0
customer_name              0
discount                   0
market                     0
order_date                 0
order_id                   0
order_priority             0
product_id                 0
product_name               0
profit                     0
quantity                   0
region                     0
row_id                     0
sales                      0
segment                    0
ship_date                  0
ship_mode                  0
shipping_cost              0
state                      0
sub_category               0
year                       0
market2                    0
weeknum                    0
delivery_days              0
profit_margin              0
month                      0
month_no                   0
quarter                    0
day                        0
week                       0
is_weekend                 0
discount_band              0
loss_order                 0
high_discount              0
sales_bucket               0
profit_bucket              0
shipping_cost_bucket       0
average_order_value        0
shipping_cost_pct          0
discount_amount            0
net_sales                  0
profit_status              0
delivery_status            0
profit_per_unit            0
inflation_rate          1299
gdp_growth               172
dtype: int64

In [17]:
final_df.to_csv(
    "../Data/Processed/final_retail_dataset.csv",
    index=False,
    encoding="utf-8-sig"
)

In [18]:
final = pd.read_csv("../Data/Processed/final_retail_dataset.csv")

final.head()

,category,city,country,customer_id,customer_name,discount,market,order_date,order_id,order_priority,...,shipping_cost_bucket,average_order_value,shipping_cost_pct,discount_amount,net_sales,profit_status,delivery_status,profit_per_unit,inflation_rate,gdp_growth
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.0,US,07-01-2011,CA-2011-130813,High,...,Medium,6.333333,23.000000,0.0,19.0,Profit,Fast,3.1104,3.156842,1.564407
1,Office Supplies,Los Angeles,United States,MV-174854,Mark Van Huff,0.0,US,21-01-2011,CA-2011-148614,Medium,...,Low,9.500000,4.947368,0.0,19.0,Profit,Normal,4.6464,3.156842,1.564407
2,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,05-08-2011,CA-2011-118962,Medium,...,Low,7.000000,8.619048,0.0,21.0,Profit,Normal,3.2806,3.156842,1.564407
3,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,05-08-2011,CA-2011-118962,Medium,...,Medium,55.500000,4.135135,0.0,111.0,Profit,Normal,26.6304,3.156842,1.564407
4,Office Supplies,Los Angeles,United States,AP-109154,Arthur Prichep,0.0,US,29-09-2011,CA-2011-146969,High,...,Low,6.000000,22.000000,0.0,6.0,Profit,Normal,3.1104,3.156842,1.564407

In [20]:
pip install pymysql

Collecting pymysql
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.0
Note: you may need to restart the kernel to use updated packages.

In [23]:
import pandas as pd
from sqlalchemy import create_engine
from urllib.parse import quote_plus

# 1. Load your dataset
file_path = r"C:\Users\SHARVARI\Downloads\Retail_Profit_Leakage_Project\Data\Processed\final_retail_dataset.csv"
df = pd.read_csv(file_path)

# 2. Safely encode the password (handles special characters like @)
password = quote_plus("Sharvari@18006")

# 3. Setup connection to your local MySQL server
engine = create_engine(f"mysql+pymysql://root:{password}@localhost:3306/retail_profit_leakage")

# 4. Append the data into your existing table
df.to_sql(name='final_retail_dataset', con=engine, if_exists='append', index=False)
print("Data successfully imported into MySQL!")

Data successfully imported into MySQL!